apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kestrel-operator-to-hubble-relay
  namespace: gke-managed-dpv2-observability
spec:
  podSelector:
    matchLabels:
      app: hubble-relay
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kestrel-ai
      podSelector:
        matchLabels:
          app: kestrel-operator
    ports:
    - protocol: TCP
      port: 4245
